# Generated by Django 3.2.11 on 2022-01-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratinghome', '0005_rename_tag_rateinfo_tag_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='rateinfo',
            name='pID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
