# Generated by Django 3.2.11 on 2022-01-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_alter_place_rating_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='ratings',
        ),
    ]
