<<<<<<< HEAD
# Generated by Django 3.2.11 on 2022-01-27 07:36
=======
# Generated by Django 3.2.5 on 2022-01-27 07:25
>>>>>>> 77835ee45b953ca5aa2cd126e129bd1db913555d

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_alter_place_rating_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='ratings',
        ),
    ]
