# Generated by Django 3.2.11 on 2022-01-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_alter_places_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destimagesfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='destimages')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='destination.places')),
            ],
        ),
        migrations.DeleteModel(
            name='destimages',
        ),
    ]
